### ISSUE TITLE
php装了redis 扩展

### ISSUE THREAD

**Issue by tubimasky** [Instrye/tiebarobot#3]
进去还是500 错误 
是否还需要别的配置
config.inc.php.template 里的bduss 也修改了

**Comment by Instrye** [comment]
百度删帖增加了其他的限制,这个插件已经失效了

**Comment by nyufeng** [comment]
测试无异常,你该不会 config.inc.php.template 直接用,没有去掉 .template ?

**Comment by tubimasky** [comment]
就是最后的后缀名没删 看了代码才发现 
昨天忘了上来回复

**Comment by nyufeng** [comment]
今天更新了一下，你也可以更新一下
