### ISSUE TITLE
2楼触发content_not_have关键字，却会把主楼删除

### ISSUE THREAD

**Issue by black2xsky** [Instrye/tiebarobot#4]
2楼触发content_not_have关键字，却会把主楼删除，然而标题和1楼并未触发title_must和content_not_have关键字

**Comment by nyufeng** [comment]
问题没有复现,能否提供测试内容或测试帖子,是否是最新代码?

**Comment by nyufeng** [comment]
title_must 是 标题必须含有,如果设置的话,我看整个版本包含的没几个,全部都会被删除。

**Comment by black2xsky** [comment]
看你的回复我就更迷惑了，title_must 关键字是触发就删除还是触发就保留？
第二个问题是2楼触发content_not_have，主楼正常不违规却被删除，这个就更不清楚了

**Comment by nyufeng** [comment]
title_must 如果标题内不含有,就删除 例： 修电脑找xxxx  (不删除)； 电脑找xxxx (删除)。
第二个问题可能是因为你对 title_must 的误解而产生的。

**Comment by black2xsky** [comment]
感谢回复指导，我再试试
